name: Test && Build

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: |
          cp CI/ESS/docker-compose.gitlab.yaml docker-compose.yaml
          docker-compose down --remove-orphans
          docker-compose pull
          docker-compose up --build --exit-code-from scicat-backend
          docker-compose down

  build:
    name: Build and push Docker image with branch tag
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # For debugging capture the selected branch
      - name: Branch
        run: echo "Branch ${{ github.head_ref }}"

      # Replace all slashes with underscore because github container registry does't accept slashes as valid tag names
      - name: Extract branch name without slashes
        id: extract_branch
        shell: bash
        run: |
          # Extract branch name
          BRANCH_NAME=${{ github.head_ref }}

          # set output variable accessible in the action
          echo ::set-output name=branch::${BRANCH_NAME} | sed 's/\//\_/g'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/scicatproject/backend:${{ steps.extract_branch.outputs.branch }}
